language: node_js
node_js:
  - "14.15.0"
branches:
  only:
    - main
cache:
  npm: true

install:
  - npm ci

script:
  - npm run build

after_script:
  - rsync -r --delete-after --quiet build/*  travis@lulaoshi.info:$TARGET_DIR

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
  ssh_known_hosts: lulaoshi.info

sudo: false

notifications:
  email: false

before_install:
  - openssl aes-256-cbc -K $encrypted_6e245bcd2662_key -iv $encrypted_6e245bcd2662_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 700 ~/.ssh
  - chmod 600 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
