language: ruby
rvm:
- 2.6.3
script:
- chmod +x ./script/cibuild.sh
- "./script/cibuild.sh"
after_script:
- rsync -azr _site/*  travis@$IP:$TARGET_DIR
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
  ssh_known_hosts: 154.8.160.59
sudo: false
cache: bundler
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_6e245bcd2662_key -iv $encrypted_6e245bcd2662_iv -in id_rsa.enc -out .ssh/id_rsa -d
- chmod 700 .ssh
- chmod 600 .ssh/id_rsa
- eval "$(ssh-agent -s)"
- ssh-add .ssh/id_rsa
