# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 皮皮鲁的科技星球
email: luweizheng36@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  皮皮鲁的科技星球
baseurl: ""
url: "https://lulaoshi.info"

theme: minimal-mistakes-jekyll
locale: zh-CN

# logo: "/assets/img/favicon.ico"
baidu_site_verification: Lsxugw73ju

# set permalink globally
permalink: /blog/:year/:month/:day/:title:output_ext

paginate: 5 # amount of posts to show
paginate_path: /page:num/

# head_scripts:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-katex
  - jekyll-paginate
  - jekyll-sitemap

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      related: true
      show_date: true
      toc: true
  - scope:
      path: "flink"
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      toc: true
      sidebar:
        nav: "flink"
  - scope:
      path: "gpu"
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      toc: true
      sidebar:
        nav: "gpu"
  - scope:
      path: "machine-learning"
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      toc: true
      sidebar:
        nav: "ml"

# Site Author
author:
  name             : "皮皮鲁"
  avatar           : "/assets/img/avatar.svg"
  bio              : "中国人民大学计算平台老师，主要研究领域为大数据和高性能计算。曾在小米大数据等一线互联网公司工作。"
  location         : "北京"
  email            : "luweizhen36@hotmail.com"
  links:
    - label: "邮箱"
      icon: "fas fa-fw fa-envelope-square"
      # url: "mailto:luweizhen36@hotmail.com"
    - label: "网站"
      icon: "fas fa-fw fa-link"
      url: "https://lulaoshi.info"
    - label: "微信"
      icon: "fab fa-fw fa-weixin"
      # url: "https://twitter.com/"
    - label: "知乎"
      icon: "fab fa-fw fa-zhihu"
      url: "https://www.zhihu.com/people/steven-lu-08"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/luweizheng"

# Reading Files
include:
  - .htaccess
  - _pages
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - script/
  - "*.idea/"
  - "*.jekyll-cache/"
  - ".ssh/"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn

