# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 鲁老师的技术分享
email: luweizheng36@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  皮皮鲁的技术分享
baseurl: ""
url: "https://lulaoshi.info"

# markdown latex
markdown: kramdown
kramdown:
  math_engine: mathjax

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "flink"
    values:
      layout: document
      breadcrumb-topname: "Flink教程"
      breadcrumb-topurl: "/flink/"

  - scope:
      path: "gpu"
    values:
      layout: document
      sidebar: "sidebar_gpu"
      breadcrumb-topname: "GPU快速教程"
      breadcrumb-topurl: "/gpu/"

  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "blogdetail"
#      sidebar: "sidebar-blog"
      breadcrumb-topname: "文章"
      breadcrumb-topurl: "/blog/"
      permalink: "/blog/:year/:month/:day/:title:output_ext"
  -
    scope:
      path: ""
    values:
      layout: default
      topnav: topnav


# UI text
uistring:
  tableofcontents: 目录
  expandall: 开启所有标签
  collapseall: 关闭所有标签
  title: "鲁老师" # Displays as site title on top nav bar and on site metadata
  description: A guide for technical writers and engineers learning how to document APIs  # Displays as site description meta
  products: Products
  docindex_product: Product
  docindex_startpage: Starting page

exclude:
  - script/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
